version: "3.8"

services:
  keepa_bot:
    build: .
    container_name: keepa_telegram_bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./backups:/app/backups
      # Use tmpfs for chrome-data to ensure ephemeral storage
      - type: tmpfs
        target: /app/chrome-data
        tmpfs:
          size: 256M
    env_file:
      - .env
    environment:
      - CHROME_USER_DATA_DIR=/app/chrome-data
    # Add proper shutdown process
    stop_grace_period: 30s
