version: "3.8"

services:
  keepa_bot:
    build: .
    container_name: keepa_telegram_bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./backups:/app/backups
      - ./chrome-sessions:/app/chrome-sessions
    env_file:
      - .env
    environment:
      - CHROME_USER_DATA_DIR=/app/chrome-sessions
    # Add proper shutdown process
    stop_grace_period: 30s
